name: Smart ASA Build and Test

on: [push]

jobs:
  build-and-test:
    name: Build & Test Smart ASA
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4
        cache: 'pipenv'

    - name: Install dependencies
      run: |
        pipenv install --deploy --dev
    - uses: pre-commit/action@v2.0.3
      name: "Linters and formatters check"
      with:
        extra_args: --all-files

    - name: Run Algorand Sandbox
      run: |
        docker run -d -p 4001:4001 -p 4002:4002 matteojug/algorand-sandbox-dev:3.7.2

    - name: Sleep to allow the sandbox to start
      run: sleep 10

    - name: Run pytest
      run: pipenv run pytest
